[build]
  command = "npm install && node ./node_modules/vite/bin/vite.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/pf/*"
  to = "https://playerflix.ink/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/wp/*"
  to = "https://watchplayer.xyz/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
